CREATE TABLE products (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    kode VARCHAR(50) NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    price INT UNSIGNED NOT NULL,
    stock INT UNSIGNED NOT NULL DEFAULT 0,
    id_kategori BIGINT UNSIGNED NULL,
    tanggal_kadaluwarsa DATE NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_products_kategori
        FOREIGN KEY (id_kategori) REFERENCES categories(id)
        ON DELETE SET NULL
);