CREATE TABLE products (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    stock DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0,
    id_kategori BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_products_kategori
        FOREIGN KEY (id_kategori) REFERENCES categories(id)
        ON DELETE SET NULL
);